#Created by ZZHow(ZZHow1024) on 2024/6/23.
#演示整型的数据类型
#使用 TINYINT 演示范围
#表的字符集、校验规则 和 存储引擎使用默认
#如果没有指定 unsigned 则 TINYINT 就是有符号的
CREATE TABLE t3(id TINYINT);
CREATE TABLE t4(id TINYINT UNSIGNED);

#添加数据
INSERT INTO t3 VALUES(-129);
INSERT INTO t3 VALUES(-128);
INSERT INTO t3 VALUES(128);
INSERT INTO t3 VALUES(127);
INSERT INTO t4 VALUES(-3);
INSERT INTO t4 VALUES(0);
INSERT INTO t4 VALUES(256);
INSERT INTO t4 VALUES(255);

#查询数据
SELECT * FROM t3;
SELECT * FROM t4;